### ISSUE TITLE
User can look up monsters with their name and displays information once submitted

### ISSUE THREAD

**Issue by jnsangalang** [jnsangalang/monsters-and-spells-oh-my#1]
## ⚙️ Feature
User can look up monsters using ‘name of monster’

> ##### What capability will users have when this feature is merged?

allows users to look up monsters by name.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After typing in the name, the monster's information will be displayed, from description to abilities

Allow users to look up monsters by typing in the monster's name in the search bar.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/jnsangalang/front-end-project/assets/157412933/005f6d13-936d-4975-bce1-1982c4b8a8df)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create HTML and CSS to reflect layout of main page, ensuring responsive layout with both mobile and desktop views
- [x] Create button that takes user to page with search bar, allowing user input.
- [x] Create function, viewSwap, to allow for switching of views based on which button is clicked on.
- [x] Add an event listener for 'monster search' button, to enable view swapping to reveal search bar.
- [x] Create async function, that allows the retrieval of information and displaying wanted information within a text box.
- [x] Create submit button, add an event listener to allow submission to trigger GET async function to retrieve information from API.
- [x] create a text box that appears and has information about the monster after user submits 'monster name'.
- [x] make sure function of 'submit button' to ensure when user searchers for a different monster, it will replace current monster information with new monster. 
- [x] adjust data retrieval, to retrieve specific properties from object, and display them on screen
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
