### ISSUE TITLE
User can look up spells by spell names and displays information once submitted

### ISSUE THREAD

**Issue by jnsangalang** [jnsangalang/monsters-and-spells-oh-my#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [x] Create async function, that allows the retrieval of SPELL information and displaying wanted information within a text box.
- [x] Add an event listener for 'spell search' button, to enable view swapping to reveal search bar for spells.
- [x] Create render SPELL information function, that displays wanted information within a text box.
- [x] Create submit button (For SPELLS), add an event listener to allow submission to trigger GET async function to retrieve information from API.
- [x] create a text box that appears and has information about the monster after user submits 'spell name'.
- [x] make sure function of 'submit button' to ensure when user searchers for a different Spell, it will replace current monster information with new monster.
- [x] adjust CSS to ensure uniformity with other views and information stylings
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
