### ISSUE TITLE
User can add spells to their list

### ISSUE THREAD

**Issue by jnsangalang** [jnsangalang/monsters-and-spells-oh-my#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add spell to a list, and have it display within spell list view page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

a "plus" button will be added to the spell display once a spell name is searched. Once the button is pressed, it will allow the user to add the spell to a spell list. When clicking the "view spell list" button, it will take the user to the current list of spells.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/jnsangalang/front-end-project/assets/157412933/a55830fa-b2cf-464b-9892-c0d1579bf9c2)

![image](https://github.com/jnsangalang/front-end-project/assets/157412933/e103a068-808f-452d-80c8-21c4a6e783ec)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] ...
- [x] create button on spell information that is displayed, to allow user to add spell to list
- [x] create eventlistener on add spell button, that stores  the resulting information into an object, assign spell ID property to the object.
- [x] increment the next spell ID for the subsequent spell
- [x] add the object to the beginning of array of spells
- [x] within data.js create before unload event listener, to window, that  serializes data as JSON and stores JSON within localStorage
- [x] within data.js, create conditional statement to check of there is a JSON model stored in localStorage
- [x] parse the data if present, and assign it to data variable, to allow for continuing of adding spells to existing list
- [x] double check to ensure the data model is being save to localStorage before each page reload
- [x] create 'minus' button for each spell card
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
