### ISSUE TITLE
User can delete spells from their lists

### ISSUE THREAD

**Issue by jnsangalang** [jnsangalang/monsters-and-spells-oh-my#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to delete a spell from their spell list, by  clicking the 'minus' button

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once 'minus' button is clicked, it will remove the spell from the list, and localStorage data so it does not persist

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/jnsangalang/front-end-project/assets/157412933/96ac9cd4-21b8-4ea4-a740-1fbc13fd58b7)

![image](https://github.com/jnsangalang/front-end-project/assets/157412933/a2049716-7089-4b33-8c02-cb8146b7df36)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add event listener to 'minus' button to loop through array and find current event target name
- [x] make sure event listener of 'minus' button removes the DOM tree of the selected spell.
- [x] create function that toggles whether or not spell list is empty, which displays text/image when no spells are in the list
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
